# Generated by Django 5.1 on 2024-08-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='education_office',
            field=models.CharField(default='전라남도교육청', max_length=100),
            preserve_default=False,
        ),
    ]
