# Generated by Django 5.1 on 2024-08-31 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_school_education_office'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
