# Generated by Django 5.1 on 2024-09-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='role',
            field=models.CharField(choices=[('본청', '본청 관리자'), ('지역청', '지역청 관리자'), ('학교', '학교 관리자'), ('user', '일반 사용자')], default='user', max_length=15),
        ),
    ]
