# Generated by Django 5.1 on 2024-09-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_school_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='role',
        ),
    ]
